name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: build
        # You may pin to the exact commit or the version.
        # uses: cross-the-world/ssh-pipeline@7f022867934a210af826af99ef80d96f03a094d5
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          # ssh remote host
          host: 118.27.109.186
          # ssh remote port
          port: 65535 # optional, default is 22
          # ssh remote user
          user: actions
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.VPS_SSH_KEY }} # optional
          # ssh remote password
          pass: ${{ secrets.VPS_SSH_PASS }}
          # execute commands on ssh
          script: |
            cd /home/actions/src
            git pull https://github.com/white-lucida/discord_bot.git
            export DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} FRIEND_CODE_CHANNEL_ID=${{ secrets.FRIEND_CODE_CHANNEL_ID }} GUILD_ID=${{ secrets.GUILD_ID }} INTRODUCTION_CHANNEL_ID=${{ secrets.INTRODUCTION_CHANNEL_ID }} THREAD_PORTAL_CHANNEL_ID=${{ secrets.THREAD_PORTAL_CHANNEL_ID }} BOT_OPT_OUT_ROLE_ID=${{ secrets.BOT_OPT_OUT_ROLE_ID }}
            npm install
            curl -H "Content-Type: application/json" -X POST -d '{"content": "リリースされました！ https://github.com/white-lucida/discord_bot/releases/latest"}'  "https://discord.com/api/webhooks/902884706331287663/emAQaVD-wNctx10sB0HOwhCzEqq8ZIs4coG65r6gdxNWDmFfkzvjtiy3cy-xIcn_aP9g"
            nohup npm run start &
